apiVersion: batch/v1
kind: Job
metadata:
  name: glm4
  annotations: 
    model_name: "glm4"
    data_size: 40
    epoch: 100
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - args:
        - --model-name
        - glm4
        - --model-path
        - /cyq/models/THUDM/glm-4-9b-chat
        command:
        - python
        - /cyq/test_demo/llm_cycle.py
        image: bencyq/glm4:202503071531
        name: glm4
      restartPolicy: Never