apiVersion: batch/v1
kind: Job
metadata:
  name: resnet50-bs64-512x512-onnx
  annotations:
    model_name: "resnet50_bs64_512x512"
    data_size: "20"
    epoch: "20"
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - args:
        - --model-name
        - resnet50_bs64_512x512
        - --model-path
        - /data/cyq/hase/model_zoo/models
        - --epoch
        - "20"
        command:
        - python
        - run_onnx_model.py
        image: bencyq/nnmeter:202603311054
        name: onnxruntime-container
        workingDir: /data/cyq/hase/model_zoo
        volumeMounts:
        - mountPath: /data/cyq
          name: data-cyq
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: data-cyq
        hostPath:
          path: /data/cyq
          type: Directory
