apiVersion: batch/v1
kind: Job
metadata:
  name: vgg16
  annotations: 
    model_name: "vgg16"
    data_size: 20
    epoch: 1000
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - args:
        - --model-name
        - vgg16
        - --model-path
        - /cyq/models/resnet/vgg16.pth
        - --images-path
        - /cyq/datasets/animals/main/
        command:
        - python
        - /cyq/test_demo/vgg_cycle.py
        image: pytorch/pytorch:2.2.0-cuda11.8-cudnn8-runtime
        name: pytorch-container
        resources:
          limits:
            k8s.amazonaws.com/vgpu: 1
        volumeMounts:
        - mountPath: /cyq
          name: cyq-volume
        - mountPath: /tmp/nvidia-mps
          name: nvidia-mps
      hostIPC: true
      nodeSelector:
        kubernetes.io/hostname: node16
      restartPolicy: Never
      volumes:
      - hostPath:
          path: /data/cyq
          type: Directory
        name: cyq-volume
      - hostPath:
          path: /tmp/nvidia-mps
        name: nvidia-mps
