apiVersion: batch/v1
kind: Job
metadata:
  name: vgg16
  annotations: 
    model_name: "vgg16"
    data_size: 20
    epoch: 1000
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - args:
        - --model-name
        - vgg16
        - --model-path
        - /cyq/models/vgg/vgg16.pth
        - --images-path
        - /cyq/datasets/animals/main/
        command:
        - python
        - /cyq/test_demo/vgg_epoch.py
        image: bencyq/infer:202503071541
        name: pytorch-container
      restartPolicy: Never