apiVersion: batch/v1
kind: Job
metadata:
  name: yolov8n
  annotations: 
    model_name: "yolov8n"
    data_size: 30
    epoch: 1000
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - args:
        - --model-name
        - yolov8n
        - --model-path
        - /cyq/models/yolov8/yolov8n.pt
        - --images-path
        - /cyq/datasets/Mapillary_Vistas/sorted_images/
        command:
        - python
        - /cyq/test_demo/yolo_epoch.py
        image: bencyq/yolo:202503071542
        name: yolov8n
      restartPolicy: Never