apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    data_size: "15"
    epoch: "10448"
    model_name: resnet152
  creationTimestamp: null
  name: "002"
spec:
  backoffLimit: 4
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - args:
        - --model-name
        - resnet152
        - --model-path
        - /cyq/models/resnet/resnet152.pth
        - --images-path
        - /cyq/datasets/animals/main/
        command:
        - python
        - /cyq/test_demo/resnet_cycle.py
        image: pytorch/pytorch:2.2.0-cuda11.8-cudnn8-runtime
        name: pytorch-container
        resources:
          limits:
            k8s.amazonaws.com/vgpu: "1"
        volumeMounts:
        - mountPath: /cyq
          name: cyq-volume
        - mountPath: /tmp/nvidia-mps
          name: nvidia-mps
      hostIPC: true
      nodeSelector:
        kubernetes.io/hostname: node16
      restartPolicy: Never
      volumes:
      - hostPath:
          path: /data/cyq
          type: Directory
        name: cyq-volume
      - hostPath:
          path: /tmp/nvidia-mps
        name: nvidia-mps
status: {}
