apiVersion: batch/v1
kind: Job
metadata:
  name: "023"
  annotations:
    model_name: "vgg13_bs128_224x224"
    data_size: "20"
    epoch: "2553"
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - args:
        - --model-name
        - vgg13_bs128_224x224
        - --model-path
        - /data/cyq/hase/model_zoo/models
        - --epoch
        - "2553"
        command:
        - python
        - run_onnx_model.py
        image: bencyq/nnmeter:202603311054
        name: onnxruntime-container
        workingDir: /data/cyq/hase/model_zoo
        volumeMounts:
        - mountPath: /data/cyq
          name: data-cyq
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: data-cyq
        hostPath:
          path: /data/cyq
          type: Directory
