apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    data_size: "0"
    epoch: "5764"
    model_name: yolov8n
  creationTimestamp: null
  name: "036"
spec:
  backoffLimit: 4
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - args:
        - --model-name
        - yolov8n
        - --model-path
        - /cyq/models/yolov8/yolov8n.pt
        - --images-path
        - /cyq/datasets/Mapillary_Vistas/sorted_images/
        command:
        - python
        - /cyq/test_demo/yolo_epoch.py
        image: bencyq/yolo:202503071542
        name: yolov8n
        resources: {}
      restartPolicy: Never
status: {}
