apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    data_size: "0"
    epoch: "5773"
    model_name: resnet50
  creationTimestamp: null
  name: "084"
spec:
  backoffLimit: 4
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - args:
        - --model-name
        - resnet50
        - --model-path
        - /cyq/models/resnet/resnet50.pth
        - --images-path
        - /cyq/datasets/animals/main/
        command:
        - python
        - /cyq/test_demo/resnet_epoch.py
        image: bencyq/infer:202503071541
        name: pytorch-container
        resources: {}
      restartPolicy: Never
status: {}
