apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    data_size: "0"
    epoch: "84"
    model_name: glm4
  creationTimestamp: null
  name: "115"
spec:
  backoffLimit: 4
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - args:
        - --model-name
        - glm4
        - --model-path
        - /cyq/models/THUDM/glm-4-9b-chat
        command:
        - python
        - /cyq/test_demo/llm_cycle.py
        image: bencyq/glm4:202503071531
        name: glm4
        resources: {}
      restartPolicy: Never
status: {}
