apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    data_size: "0"
    epoch: "5958"
    model_name: densenet169
  creationTimestamp: null
  name: "122"
spec:
  backoffLimit: 4
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - args:
        - --model-name
        - densenet169
        - --model-path
        - /cyq/models/densenet/densenet169.pth
        - --images-path
        - /cyq/datasets/animals/main/
        command:
        - python
        - /cyq/test_demo/densenet_epoch.py
        image: bencyq/infer:202503071541
        name: pytorch-container
        resources: {}
      restartPolicy: Never
status: {}
