apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    data_size: "12"
    epoch: "13836"
    model_name: yolov8x
  creationTimestamp: null
  name: "14"
spec:
  backoffLimit: 4
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - args:
        - --model-name
        - yolov8x
        - --model-path
        - /cyq/models/yolov8/yolov8x.pt
        - --images-path
        - /cyq/datasets/Mapillary_Vistas/sorted_images/
        command:
        - python
        - /cyq/test_demo/yolo_cycle.py
        image: bencyq/sam:202411072002
        name: yolov8x
        resources:
          limits:
            k8s.amazonaws.com/vgpu: "1"
        volumeMounts:
        - mountPath: /cyq
          name: cyq-volume
        - mountPath: /tmp/nvidia-mps
          name: nvidia-mps
      hostIPC: true
      nodeSelector:
        kubernetes.io/hostname: node16
      restartPolicy: Never
      volumes:
      - hostPath:
          path: /data/cyq
          type: Directory
        name: cyq-volume
      - hostPath:
          path: /tmp/nvidia-mps
        name: nvidia-mps
status: {}
