apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    data_size: "26"
    epoch: "136"
    model_name: qwen2.5
  creationTimestamp: null
  name: "15"
spec:
  backoffLimit: 4
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - args:
        - --model-name
        - qwen2.5
        - --model-path
        - /cyq/models/Qwen/Qwen2.5-7B-Instruct
        command:
        - python
        - /cyq/test_demo/llm_cycle.py
        image: bencyq/llm_with_flask:202410242310
        name: qwen2.5
        resources:
          limits:
            k8s.amazonaws.com/vgpu: "1"
        volumeMounts:
        - mountPath: /cyq
          name: cyq-volume
        - mountPath: /tmp/nvidia-mps
          name: nvidia-mps
      hostIPC: true
      nodeSelector:
        kubernetes.io/hostname: node16
      restartPolicy: Never
      volumes:
      - hostPath:
          path: /data/cyq
          type: Directory
        name: cyq-volume
      - hostPath:
          path: /tmp/nvidia-mps
        name: nvidia-mps
status: {}
