apiVersion: batch/v1
kind: Job
metadata:
  name: densenet121
  annotations: 
    model_name: "densenet121"
    data_size: 20
    epoch: 10000
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - args:
        - --model-name
        - densenet121
        - --model-path
        - /cyq/models/densenet/densenet121.pth
        - --images-path
        - /cyq/datasets/animals/main/
        command:
        - python
        - /cyq/test_demo/densenet_epoch.py
        image: bencyq/infer:202503071541
        name: pytorch-container
      restartPolicy: Never

