apiVersion: batch/v1
kind: Job
metadata:
  name: llama3
  annotations: 
    model_name: "llama3"
    data_size: 40
    epoch: 5
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - args:
        - --model-name
        - llama3
        - --model-path
        - /cyq/models/shenzhi-wang/Llama3.1-8B-Chinese-Chat
        command:
        - python
        - /cyq/test_demo/llm_cycle.py
        image: bencyq/llama3:202503071526
        name: llama3
      restartPolicy: Never