apiVersion: batch/v1
kind: Job
metadata:
  name: qwen3
  annotations: 
    model_name: "qwen2.5"
    data_size: 40
    epoch: 5
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - args:
        - --model-name
        - qwen2.5
        - --model-path
        - /cyq/models/Qwen/Qwen2.5-7B-Instruct
        command:
        - python
        - /cyq/test_demo/llm_cycle.py
        image: bencyq/qwen2.5:202503071530
        name: qwen
      restartPolicy: Never
      