apiVersion: batch/v1
kind: Job
metadata:
  name: resnet18
  annotations: 
    model_name: "resnet18"
    data_size: 20
    epoch: 10000
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - args:
        - --model-name
        - resnet18
        - --model-path
        - /cyq/models/resnet/resnet18.pth
        - --images-path
        - /cyq/datasets/animals/main/
        command:
        - python
        - /cyq/test_demo/resnet_epoch.py
        image: bencyq/infer:202503071541
        name: pytorch-container
      restartPolicy: Never